//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace koosteteht.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("koosteteht.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font.
        /// </summary>
        public static string changeFont {
            get {
                return ResourceManager.GetString("changeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Decrease.
        /// </summary>
        public static string fontDec {
            get {
                return ResourceManager.GetString("fontDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Increase.
        /// </summary>
        public static string fontInc {
            get {
                return ResourceManager.GetString("fontInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Canvas Size.
        /// </summary>
        public static string menuCanvas {
            get {
                return ResourceManager.GetString("menuCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string menuClose {
            get {
                return ResourceManager.GetString("menuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string menuCopy {
            get {
                return ResourceManager.GetString("menuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Extras.
        /// </summary>
        public static string menuExtra {
            get {
                return ResourceManager.GetString("menuExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string menuFile {
            get {
                return ResourceManager.GetString("menuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font.
        /// </summary>
        public static string menuFont {
            get {
                return ResourceManager.GetString("menuFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Format.
        /// </summary>
        public static string menuFormat {
            get {
                return ResourceManager.GetString("menuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manual.
        /// </summary>
        public static string menuManual {
            get {
                return ResourceManager.GetString("menuManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Project.
        /// </summary>
        public static string menuNew {
            get {
                return ResourceManager.GetString("menuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Olympic Rings.
        /// </summary>
        public static string menuOlympic {
            get {
                return ResourceManager.GetString("menuOlympic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string menuOpen {
            get {
                return ResourceManager.GetString("menuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string menuPaste {
            get {
                return ResourceManager.GetString("menuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print.
        /// </summary>
        public static string menuPrint {
            get {
                return ResourceManager.GetString("menuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string menuRedo {
            get {
                return ResourceManager.GetString("menuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichText.
        /// </summary>
        public static string menuRich {
            get {
                return ResourceManager.GetString("menuRich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save As.
        /// </summary>
        public static string menuSave {
            get {
                return ResourceManager.GetString("menuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string menuUndo {
            get {
                return ResourceManager.GetString("menuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project. Are you sure? All progress will be lost..
        /// </summary>
        public static string newProject {
            get {
                return ResourceManager.GetString("newProject", resourceCulture);
            }
        }
    }
}
